n = (input('\033[1;34mDigite\033[m \033[1;31mum \033[4;35mvalor\033[m: '))
print('O tipo primitivo desse valor é ', type(n))
print(n, 'é um número?', n.isalnum())
print(n, 'É um numérico?', n.isnumeric())
print(n, 'É alfabético?', n.isalpha())
print(n, 'È um dígito?', n.isdigit())
print(n, 'É decimal?', n.isdecimal())
print(n, 'é minúsculo?', n.islower())
print('É espaço?', n.isspace())
